name = "youtube-extractor-backend"
main = "src/index.js"
compatibility_date = "2023-11-21"
compatibility_flags = [ "nodejs_compat" ] # <--- THÊM DÒNG NÀY VÀO

[vars]
# Chúng ta sẽ không đặt các biến nhạy cảm ở đây.
# Thay vào đó, chúng ta sẽ thêm chúng dưới dạng "Secrets" trong Dashboard của Cloudflare.
FRONTEND_URL = "https://your-frontend-url.pages.dev" # CẬP NHẬT SAU KHI DEPLOY FRONTEND
PRICE_ID_MONTHLY="price_..." # ID giá từ Stripe
PRICE_ID_YEARLY="price_..." # ID giá từ Stripe
