name = "youtube-extractor-backend"
main = "src/index.js"
compatibility_date = "2024-09-23"

[vars]
FRONTEND_URL = "https://your-frontend-url.pages.dev"
PRICE_ID_MONTHLY="price_..."
PRICE_ID_YEARLY="price_..."
